model = "gpt-5.3-codex"
approval_policy = "never"
sandbox_mode = "danger-full-access"
model_reasoning_effort = "high"
model_reasoning_summary_format = "experimental"
personality = "pragmatic"

[sandbox_workspace_write]
network_access = true

[features]
web_search_request = true

[shell_environment_policy]
inherit = "core"

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.1" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
